export const ONGOING_AUTHORIZATION_OPERATION_STATE_CHANGE = "ONGOING_AUTHORIZATION_OPERATION_STATE_CHANGE";
export const CLEAR_AUTHORIZATION_ERROR = "CLEAR_AUTHORIZATION_ERROR";
export const TRY_INITIALIZE = "TRY_INITIALIZE";
export const TRY_SIGN_IN_WITH_GOOGLE = "TRY_SIGN_IN_WITH_GOOGLE";
export const TRY_SIGN_IN_WITH_FACEBOOK = "TRY_SIGN_IN_WITH_FACEBOOK";
export const TRY_SIGN_OUT = "TRY_SIGN_OUT";

export const ONGOING_STREAMS_OPERATION_STATE_CHANGE = "ONGOING_STREAMS_OPERATION_STATE_CHANGE";
export const CLEAR_STREAMS_ERROR = "CLEAR_STREAMS_ERROR";
export const ON_FIREBASE_CRITICAL_SYNC_ERROR = "ON_FIREBASE_CRITICAL_SYNC_ERROR";
export const REAL_TIME_UPDATE_ERROR = "REAL_TIME_UPDATE_ERROR";
export const REAL_TIME_UPDATE = "REAL_TIME_UPDATE";
export const SUBSCRIBE_TO_STREAMS = "SUBSCRIBE_TO_STREAMS";
export const UNSUBSCRIBE_FROM_STREAMS = "UNSUBSCRIBE_FROM_STREAMS";
export const CREATE_STREAM = "CREATE_STREAM";
export const FETCH_STREAMS = "FETCH_STREAMS";
export const FETCH_STREAM = "FETCH_STREAM";
export const UPDATE_STREAM = "UPDATE_STREAM";
export const DELETE_STREAM = "DELETE_STREAM";

export const SET_NAVIGATION_METHOD = "SET_NAVIGATION_METHOD";
export const SET_HOME_SCREEN = "SET_HOME_SCREEN";
export const SET_SHOW_NAVIGATE_BACK = "SET_SHOW_NAVIGATE_BACK";
export const SET_SHOW_NAVIGATE_FORWARD = "SET_SHOW_NAVIGATE_FORWARD";
export const NAVIGATE_BACK_HOME = "NAVIGATE_BACK_HOME";
export const NAVIGATE_BACK = "NAVIGATE_BACK";
export const NAVIGATE_FORWARD = "NAVIGATE_FORWARD";
export const NAVIGATE_TO = "NAVIGATE_TO";

export const SET_SCREEN_ORIENTATION = "SET_SCREEN_ORIENTATION";
